### ISSUE TITLE
Error 404 when attempting to access website

### ISSUE THREAD

**Issue by tianxil** [kisuka/YiffSpot#102]
The web page is currently unaccessible. It only shows a 404 Error

**Comment by HahkMelot** [comment]
Same issue on my side

**Comment by JadeTheUmby** [comment]
Been having the same issue since ~1AM EST, might be the new updates happening, but it's strange that it's taking so long and the site just 404'd without warning.

**Comment by AzFoxxo** [comment]
Running local version and seems fine, tried it on Ubuntu server too to test and worked, guessing it's a deployment issue. Only possible issue off the top of my head if the server has been changed, is package versions changed and on one thing I tried it on, I manually had to upgrade npm from 9 to 10 iirc but complete guess.

**Comment by JadeTheUmby** [comment]
> Running local version and seems fine, tried it on Ubuntu server too to test and worked, guessing it's a deployment issue. Only possible issue off the top of my head if the server has been changed, is package versions changed and on one thing I tried it on, I manually had to upgrade npm from 9 to 10 iirc but complete guess.

Hm, that'd have to be it at that point. Server's have been throwing a 404 error for almost ~24 hours now, lines up a few hours after the Github was updated to show changes. Was assuming it might've been a debug oversight or something server related, there WAS a CloudHost error pop-up in the beginning, but now it just reads out '404 page not found'

**Comment by kisuka** [comment]
Sorry for the delay, should be back up now.
