### ISSUE TITLE
Small issues and feature requests/QoL

### ISSUE THREAD

**Issue by Quinten0508** [kisuka/YiffSpot#103]
Didn't want to spam a bunch of issues, so just some things I've noticed :)

* The `Your partner is typing...` message doesn't have a timeout when the user stops typing but doesn't send a message. If someone types a few letters but changes their mind, the message will show up forever on the partner's end, which can be confusing.
* If user A first disconnects and then later also blocks user B, user B will receive the `Your yiffing partner has left.` message for both actions. 
  * This second disconnect message also causes a problem if user B has already connected to a new user, C, in between the disconnect and block from user A. User B is now connected to User C, but has received the `Your yiffing partner has left.` message (from user A's late block action). This means user B can now no longer send messages to user C, because the client believes user B is not connected to any partner.
* `Your Role` and `Your Species` have the `select role` as entry, and it is seen as valid, allowing users to connect if they have it set as such.
* Move the block confirmation toast to the left hand side on browser views, so you don't have to reach to the other side of the window. Or. could also make it so you can click the block button itself twice, the second time being the confirmation.
* Auto-select the first entry when adding a kink/species/gender and searching, so one can type+enter, and/or allow for tabbing through the list of entries.

Also feature requests!
* Allow for a denylist on kinks, where users can specify kinks they do _not_ want their partner to have. Not sure if this is viable because letting users be too picky means less matches.
* Multi-select for species/kinks sections, so we don't have to open the dropdown every time we want to add a new one. 
* "true" dark theme, with `#000000` as background color for OLED devices to save on battery and better comfort in dark surroundings.

**Comment by chtseac** [comment]
For the disconnect bug, I think this line is to blame:

https://github.com/kisuka/YiffSpot/blob/master/src/server/block-partner.js#L14

And it should have checked if the partner was connected to currentUser before line 10.

It's been very frustrating whenever I get hit with the stray "has left" message while the current partner is interested and keep messaging me.

**Comment by Quinten0508** [comment]
Just gonna close this for now as most of the stuff has been implemented. I think the disconnect bug should be its own issue if people are still facing that problem, it has been more stable for me (though I'm not very frequent). Thank you so much @dancojocaru2000 ❤️
