### ISSUE TITLE
New Fetishes

### ISSUE THREAD

**Issue by kisuka** [kisuka/YiffSpot#11]
- Cuntboys
- Tentacles

**Comment by firespacer** [comment]
Are we supposed to suggest new kinks here? In case so, could you please add these?

Ageplay
Crossdressing
Deepthroat
Excessive Cum
Exhibitionism
Group Sex
Growth
Orgasm Control/Denial
Nipple Penetration
Petplay
Prostitution
Public Use
Rape
Size Difference
Voyeurism
