### ISSUE TITLE
"Blocking" potential partners doesn't appear to work

### ISSUE THREAD

**Issue by oheyimafox** [kisuka/YiffSpot#20]
I noticed that the "Block Partner" button was added. However, I seem to get the same exact partner repeatedly even after using it.

**Comment by dancojocaru2000** [comment]
I didn't get too much time to look over the server implementation, however I noticed that it uses the socket id. That id is a new one each time you refresh the page or the partener refreshes the page. Anonymity comes at a cost.

**Comment by oheyimafox** [comment]
It happens so quickly, I seriously doubt they are refreshing the page. Definitely just hitting the "find a partner" button again.

**Comment by kisuka** [comment]
I'll check it out again. I've been considering adding an extra ID that's saved in localstorage but I dunno. Feel gross to do since I like the whole anonymous aspect of it all. But I guess being able to block and have a stable RP outweighs that tbh.

**Comment by dancojocaru2000** [comment]
Maybe store it in cache so users can clear to cache to keep anonymity while making it hard enough so not everybody would do it to escape blocking...

**Comment by kisuka** [comment]
working on a whole rewrite atm. Should fix a bunch of these issues and then some.

**Comment by Seizure** [comment]
Speaking as a user of your service (Thanks!) I can tell you I wouldn't care at all about you storing a cookie so that features like this work properly. I imagine most folks would feel the same.

**Comment by oheyimafox** [comment]
Speaking as a user of your service (Thanks btw!) I can tell you I couldn't care less if you stored a cookie on my computer for the sake of having features like this work properly. I'd like to think others feel the same. Besides, if I'm so concerned with anonymity, I can just clear my cookies at the end of the session.

Of course, I can easily get around blocks by clearing cache then, but I don't think that will be a major issue.

**Comment by dancojocaru2000** [comment]
Yep. And for those extremely private, InPrivate/Private/Incognito is a way to stay private... So this seems like the best solution...

On 20 Oct 2017, at 02:15, oheyimafox <notifications@github.com<mailto:notifications@github.com>> wrote:


Speaking as a user of your service (Thanks btw!) I can tell you I couldn't care less if you stored a cookie on my computer for the sake of having features like this work properly. I'd like to think others feel the same. Besides, if I'm so concerned with anonymity, I can just clear my cookies at the end of the session.

Of course, I can easily get around blocks by clearing cache then, but I don't think that will be a major issue.

**Comment by kisuka** [comment]
Should be working now with the switch to ws.
