### ISSUE TITLE
Why not to bundle Socket.io client with rest of JS code?

### ISSUE THREAD

**Issue by ctl** [kisuka/YiffSpot#21]

**Comment by dancojocaru2000** [comment]
Downloaded from Cloudflare CDN afaik

**Comment by mememaestro** [comment]
@dancojocaru2000 , but always bundling > cdn

**Comment by dancojocaru2000** [comment]
@mememaestro For one file, CDN is better.
Also, maybe the server limits total bandwidth so one less .js maybe makes a difference.

**Comment by mememaestro** [comment]
@dancojocaru2000 lel maybe , but i'm not sure
