### ISSUE TITLE
Connection issues

### ISSUE THREAD

**Issue by arcanaabscondita** [kisuka/YiffSpot#27]
I have noticed that when i have a bump in my WiFi, like for a second i have no WiFi because bad connection, YiffSpot will go into this strange state where it thinks I have a partner, and doesn't think I have a partner at the same time.  
I get the message that I have a partner and i am in a session
I cannot type and post messages because I have no partner
I can't look for a new partner or block the non-existent partner I have
I sometimes get a message saying my non-existent partner is typing
this state after refreshing the page or closing my browser will last for several minutes (3-15)
have only tested for 5-10 minutes but the problem does not seem to go away unless I refresh or close my browser

**Comment by kisuka** [comment]
I'll be working on a reconnecting type thing to fix this soon when I have time. Basically your're connection drops and causes you to lose you connection to the yiffspot server. This causes the other partner to also see a disconnect message and be removed as your partner. The idea for the new feature is that if it detects a disconnect it'll inform each party and attempt reconnect for the next 10 - 15 seconds. After that it'll trigger the actual disconnect code.
