### ISSUE TITLE
Mobile Issue

### ISSUE THREAD

**Issue by FortunateSon12** [kisuka/YiffSpot#29]
Hi,
I was hoping that someone else would point it out but I just wanted to let you know in case you weren't already aware, for the mobile version of Yiffspot, pressing the button containing three horizontal bars which previously before the switch to WS would drop down the preferences tab, no longer functions. I have tried multiple mobile browsers, uninstalling them and trying again to no avail. Mobile browsers that open websites in desktop mode do function so I know Yiffspot is working. 
Hope this is a quick fix.

**Comment by kisuka** [comment]
Try now. I had to fix some issues on the server. Should hopefully be working now. Lemme know if you're still having issues.

**Comment by FortunateSon12** [comment]
Thanks for your continued dedication. I highly enjoy using yiffspot and I hope it gets the recognition it deserves.

**Comment by FortunateSon12** [comment]
Thanks for your continued dedication. I highly enjoy using yiffspot and I hope it gets the recognition it deserves.

**Comment by FortunateSon12** [comment]
I applaud you for fixing the server connection issue but I regret to inform you that mobile appears to still be broken. I'm considering this may have something to do on my end but I can't imagine how chrome would abruptly stop working yiffspot. Is there any chance you or an outside source can test the mobile version of yiffspot to confirm that it is either a universal problem or a user specific?

**Comment by kisuka** [comment]
It appears to be working on my phone. I'll try on a few more and see if they show any signs of the issue.
