### ISSUE TITLE
New connection Issue

### ISSUE THREAD

**Issue by FortunateSon12** [kisuka/YiffSpot#30]
So at 00:09 PST I was attempting to use yiffspot when I noticed how long I had been waiting to connect. I saw there was 38 other people using the service and it had never taken this long for someone to connect. I pulled out my phone(using the desktop browser app as mobile is still broken) and setup a parter that would be an exact match for my preferences just to see if it would connect. Two minutes later and nothing. It appears the WS update may have done more damage than good in this instance as multiple issues are presenting themselves. Hope these issues are fixed in a timely manner.

**Comment by kisuka** [comment]
Try now. I had to fix some issues on the server. Should hopefully be working now. Lemme know if you're still having issues.

**Comment by FortunateSon12** [comment]
Thanks for your continued dedication. I highly enjoy using yiffspot and I hope it gets the recognition it deserves.
