### ISSUE TITLE
Mobile window sizing issues

### ISSUE THREAD

**Issue by qdot** [kisuka/YiffSpot#39]
While the responsive layout basically works on mobile, when the chat window expands to the overflow point, it seems that the page layout doesn't know what to do with itself and starts expanding, meaning the top menu scrolls out of the frame and navigation gets awkward. This happens with both stock yiffspot and the teledildonics fork.

I think this could be fixed using viewport units for max-height/width, but this is gonna require the buggyfill package for the fucked up viewport issues on safari. https://github.com/rodneyrehm/viewport-units-buggyfill

**Comment by qdot** [comment]
Did a little bit more looking at this. For the vertical issues, it appears the navbar is the problem. Currently the chat container will max at 90vh, and in the teledildonics branch with flexbox, that's variable. However, flexbox needs height definitions all the way up the tree, so we get navbar height plus the container set to height: 100%, which pushes the content container too far down.

It might be worth making the navbar expand on swipe and collapse on connect, typing, etc?

**Comment by kisuka** [comment]
Yeah, I been meaning to re-do the navigation. I did it in a rush and it was kinda really sloppy.
