### ISSUE TITLE
Block Partner

### ISSUE THREAD

**Issue by kisuka** [kisuka/YiffSpot#4]
Add a button or link that gives user the ability to block a specific person to stop connecting with them. This action would only be limited to that session, it disappears on disconnect / leaving site.

**Comment by kisuka** [comment]
Added in 1117bf146068039a2043b2f5270cdc12b3fcb006.

**Comment by dancojocaru2000** [comment]
THANKS!
This feature is probably a live saver.

**Comment by kisuka** [comment]
No problem :) hopefully it'll help filter out some of those people that just disconnect immediately for whatever reason, lol.
