### ISSUE TITLE
502: Bad Gateway 

### ISSUE THREAD

**Issue by aleluccio2005** [kisuka/YiffSpot#42]
Hello

I have been using your site for about a week and it was going pretty smoothly

Three days ago I don't know Why but whenever I try to access your site it just takes me to an error page wich says

Error 502: Bad Gateway

I don't know if the website is down or I am banned for some reasons

Thank you

**Comment by kisuka** [comment]
Should hopefully be fixed now. fingers crossed. Did some upgrades and some error handling stuff to prevent the server from crashing.
