### ISSUE TITLE
Select All/None or a Not Option

### ISSUE THREAD

**Issue by InkDragon** [kisuka/YiffSpot#43]
Would it be possible to add an option to either select all or clear all selected Kinks and Partner's Species tags? Or an option to selectively flag some kinks as something you don't want.

Basically I wanna be able to pick out say no humans for my partners without having to pick though and select all the options when my cookies get deleted.

**Comment by kisuka** [comment]
Sure, I'll figure out a way to work this into the design when I get around to doing some updates to the site in the coming weeks.
