### ISSUE TITLE
multiple active session problem

### ISSUE THREAD

**Issue by gubba12** [kisuka/YiffSpot#50]
I keep loading up yiffspot and it says I have another active session but theres nothing else opened up. I shut down my browser and restarted my phone but nothing changed. the only abnormal thing I saw was over 300 people were online

**Comment by Hexasama** [comment]
I've been experiencing the same issue this morning (CET 8:10) I woke up because I figured there would be more people online due to time zones. I was right but, i've never seen 500 people on Yiffspot.

**Comment by gubba12** [comment]
I assumed something else. like 4chan people coming in and overloading the stuff...or something to do with ip addresses but im no computer guy

**Comment by Hexasama** [comment]
It'd be the best if there was like 500 people online every day. It's kinda hard to find partners if there is only 20 users online. However by looking at the site's state I think the problem lies in the servers. I'd be nervous as well if 500 people showd up instead of 20 of my friends. :'D

**Comment by kisuka** [comment]
You guys still having this issue? It seems something went crazy on the server. I did a restart and reinstall of the app and it seems to be okay now.
