### ISSUE TITLE
Highlight matching fetishes when you are matched with someone

### ISSUE THREAD

**Issue by oheyimafox** [kisuka/YiffSpot#52]
Currently, when you are matched with a partner, it just gives you a long block of text listing all the fetishes they have marked. Of course, this info is useful, but I think it would be even more useful if it highlighted or colored the fetishes which you both share, so that you can more easily see what you have in common at a glance.

Thanks!

**Comment by dancojocaru2000** [comment]
I opened a [PR](https://github.com/kisuka/YiffSpot/pull/58) that would highlight common kinks in blue. Let's hope it will be merged.
