### ISSUE TITLE
Missing Buld script?

### ISSUE THREAD

**Issue by AppleCanon** [kisuka/YiffSpot#99]
After going through the process of installing and running it, it gives me an error that Buld is missing, and gives me a log (attached below)
[2023-01-19T00_19_55_546Z-debug-0.log](https://github.com/kisuka/YiffSpot/files/10452291/2023-01-19T00_19_55_546Z-debug-0.log)

**Comment by AzFoxxo** [comment]
I fixed it by changing line 18 of package.json, changing buld to build and works fine for me

Here's my commit: https://github.com/kisuka/YiffSpot/commit/669e902df7068e07622348663042b9d842df0d90

**Comment by kisuka** [comment]
Fixed
